-- ============================================================================
-- BORRAR_TABLAS.sql — borrado condicional (IBM i 7.4+ DROP IF EXISTS recomendado)
-- ============================================================================
-- Creacion de tablas (un solo archivo): sql/CREAR_TABLAS.sql
-- Este script solo elimina objetos si existen, en orden compatible con FK.
-- Biblioteca: cambie solo SET SCHEMA si no es BDSUPER.
-- ============================================================================

SET SCHEMA BDSUPER;

DROP TABLE IF EXISTS PROYECTO_ESTRUCTURAS;
DROP TABLE IF EXISTS PROYECTO;
DROP TABLE IF EXISTS DATOS_GENERALES;

DROP TABLE IF EXISTS GP_DOCUMENTOS;
DROP TABLE IF EXISTS GP_CAPITALIZACIONES;
DROP TABLE IF EXISTS GP_NEGOCIACION_ACCIONES;
DROP TABLE IF EXISTS GP_PERMUTA;
DROP TABLE IF EXISTS GP_COMPRA_INMUEBLES;
DROP TABLE IF EXISTS GP_COMODATO;
DROP TABLE IF EXISTS GP_ARRENDAMIENTO;
DROP TABLE IF EXISTS GP_CARTERA_EDADES;
DROP TABLE IF EXISTS GP_FONDOS_CREDITO;
DROP TABLE IF EXISTS GP_INFRAESTRUCTURA;
DROP TABLE IF EXISTS GP_SEGUIMIENTO;
DROP TABLE IF EXISTS GP_COBERTURA_EJECUTADA;
DROP TABLE IF EXISTS GP_COBERTURA_PROYECTADA;
DROP TABLE IF EXISTS GP_FUENTE_RECURSOS;
DROP TABLE IF EXISTS GP_LOCALIZACION;
DROP TABLE IF EXISTS GP_CRONOGRAMA;
DROP TABLE IF EXISTS GP_DATOS_GENERALES;

DROP TABLE IF EXISTS SYS_CONTROL_REPORTES;
DROP TABLE IF EXISTS SYS_LOG_MODIFICACIONES;

DROP TABLE IF EXISTS GP_PROYECTOS;

DROP TABLE IF EXISTS FV_RENOVACION_URBANA;
DROP TABLE IF EXISTS FV_ADQUISICION_LOTES;
DROP TABLE IF EXISTS FV_CREDITOS_HIPOTECARIOS;
DROP TABLE IF EXISTS FV_TIPOLOGIA_VIS;
DROP TABLE IF EXISTS FV_ASPECTOS_VIS;
DROP TABLE IF EXISTS FV_SEGUIMIENTO;
DROP TABLE IF EXISTS FV_COBERTURA_PROYECTADA;
DROP TABLE IF EXISTS FV_CRONOGRAMA;

DROP TABLE IF EXISTS FV_PROYECTOS;

DROP TABLE IF EXISTS SYS_PARAMETROS;
DROP TABLE IF EXISTS SYS_ESTRUCTURAS;
