-- ============================================================================
-- SCRIPT: CREAR_TABLAS.sql
-- DESCRIPCION: Crea todas las tablas del sistema de Gestion de Proyectos
-- BASE DE DATOS: IBM DB2/AS400 (iSeries)
-- AUTOR: Equipo de Desarrollo
-- FECHA: 2026-05-02
-- ============================================================================
-- NOTA: Este script usa UUID como llave primaria para todas las tablas.
--       COD_PROYECTO es un atributo de negocio que puede cambiar.
-- Biblioteca: cambie solo la siguiente linea si no es BDSUPER (objetos sin calificador).
-- ============================================================================

SET SCHEMA BDSUPER;

-- ============================================================================
-- SECCION 1: PROYECTOS GENERALES (P-001A a P-056A)
-- ============================================================================

-- -----------------------------------------------------------------------------
-- Tabla principal de Proyectos - Llave primaria UUID
-- -----------------------------------------------------------------------------

CREATE TABLE GP_PROYECTOS (
    ID_PROYECTO VARCHAR(36) NOT NULL,
    COD_PROYECTO VARCHAR(15) NOT NULL,
    MOD_PROYECTO INTEGER NOT NULL,
    MOD_DE_INVERSION INTEGER NOT NULL,
    VAL_TOTAL_PROYECTO BIGINT NOT NULL,
    VALOR_APR_VIGENCIA BIGINT NOT NULL,
    DESCRIPCION_PROYECTO VARCHAR(4000) NOT NULL,
    OBJETIVO_PROYECTO VARCHAR(4000) NOT NULL,
    JUSTIFICACION VARCHAR(4000) NOT NULL,
    RESOLUCION_AEI INTEGER NOT NULL,
    NUM_ACTA_AEI BIGINT,
    FECHA_APR_AEI VARCHAR(8),
    NUM_CONSEJEROS INTEGER NOT NULL,
    TMP_RECUPERACION INTEGER,
    ESTUDIO_MERCADO VARCHAR(4000),
    EVALUACION_SOCIAL VARCHAR(4000),
    EVALUACION_FINANCIERA VARCHAR(4000),
    NUM_PERSONAS_REFERENCE BIGINT,
    NUM_POBLACION_AFECTADA BIGINT,
    ESTADO_PROYECTO VARCHAR(20) DEFAULT 'BORRADOR',
    FEC_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FEC_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USUARIO_CREACION VARCHAR(50),
    USUARIO_MODIFICACION VARCHAR(50),
    CONSTRAINT PK_GP_PROYECTOS PRIMARY KEY (ID_PROYECTO)
);

CREATE UNIQUE INDEX UX_GP_PROYECTOS_CODIGO ON GP_PROYECTOS(COD_PROYECTO);
CREATE INDEX IDX_GP_PROYECTOS_ESTADO ON GP_PROYECTOS(ESTADO_PROYECTO);
CREATE INDEX IDX_GP_PROYECTOS_MOD ON GP_PROYECTOS(MOD_DE_INVERSION);

COMMENT ON TABLE GP_PROYECTOS IS 'Tabla principal de proyectos - UUID como PK, COD_PROYECTO es atributo de negocio';

-- -----------------------------------------------------------------------------
-- P-001A: Estructuras Generales Proyectos de Inversion
-- -----------------------------------------------------------------------------
CREATE TABLE GP_DATOS_GENERALES (
    ID_DATO_GENERAL VARCHAR(36) NOT NULL,
    ID_PROYECTO VARCHAR(36) NOT NULL,
    OBJETIVOS_ESPECIFICOS VARCHAR(4000),
    DESCRIPCION_OBJETIVO VARCHAR(2000),
    TIEMPO_RECUPERACION INTEGER,
    TASA_DESCUENTO VARCHAR(5),
    NUMERO_BENEFICIARIOS BIGINT,
    FEC_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FEC_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_GP_DATOS_GENERALES PRIMARY KEY (ID_DATO_GENERAL),
    CONSTRAINT FK_GP_DGENERALES_PROYECTO FOREIGN KEY (ID_PROYECTO)
        REFERENCES GP_PROYECTOS(ID_PROYECTO) ON DELETE CASCADE
);

COMMENT ON TABLE GP_DATOS_GENERALES IS 'P-001A: Datos Generales del Proyecto';

-- -----------------------------------------------------------------------------
-- P-002A: Cronograma Inicial del Proyecto
-- -----------------------------------------------------------------------------
CREATE TABLE GP_CRONOGRAMA (
    ID_CRONOGRAMA VARCHAR(36) NOT NULL,
    ID_PROYECTO VARCHAR(36) NOT NULL,
    TIPO_ACTIVIDAD VARCHAR(5) NOT NULL,
    DESCRIPCION_ACTIVIDAD VARCHAR(500),
    PORCENTAJE_PROYECTADO VARCHAR(5) NOT NULL,
    FECHA_INICIO VARCHAR(8) NOT NULL,
    FECHA_TERMINACION VARCHAR(8) NOT NULL,
    UNIDAD_MEDIDA VARCHAR(50),
    CANTIDAD_PROGRAMADA BIGINT,
    VALOR_PROGRAMADO BIGINT,
    ORDEN_EJECUCION INTEGER,
    FEC_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_GP_CRONOGRAMA PRIMARY KEY (ID_CRONOGRAMA),
    CONSTRAINT FK_GP_CRONOGRAMA_PROYECTO FOREIGN KEY (ID_PROYECTO)
        REFERENCES GP_PROYECTOS(ID_PROYECTO) ON DELETE CASCADE
);

CREATE INDEX IDX_GP_CRONOGRAMA_PROYECTO ON GP_CRONOGRAMA(ID_PROYECTO);

COMMENT ON TABLE GP_CRONOGRAMA IS 'P-002A: Cronograma Inicial del Proyecto - Una fila por actividad';

-- -----------------------------------------------------------------------------
-- P-003A: Localizacion del Proyecto
-- -----------------------------------------------------------------------------
CREATE TABLE GP_LOCALIZACION (
    ID_LOCALIZACION VARCHAR(36) NOT NULL,
    ID_PROYECTO VARCHAR(36) NOT NULL,
    DEPARTAMENTO VARCHAR(100) NOT NULL,
    MUNICIPIO VARCHAR(100) NOT NULL,
    DIRECCION VARCHAR(200),
    BARRIO VARCHAR(100),
    TELEFONO VARCHAR(30),
    CONTACTO VARCHAR(50),
    FECHA_INICIO_OPERACION VARCHAR(8),
    LATITUD DECIMAL(10, 8),
    LONGITUD DECIMAL(11, 8),
    FEC_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_GP_LOCALIZACION PRIMARY KEY (ID_LOCALIZACION),
    CONSTRAINT FK_GP_LOCALIZACION_PROYECTO FOREIGN KEY (ID_PROYECTO)
        REFERENCES GP_PROYECTOS(ID_PROYECTO) ON DELETE CASCADE
);

COMMENT ON TABLE GP_LOCALIZACION IS 'P-003A: Localizacion del Proyecto';

-- -----------------------------------------------------------------------------
-- P-004C: Fuente de Recursos y Centro de Costos
-- -----------------------------------------------------------------------------
CREATE TABLE GP_FUENTE_RECURSOS (
    ID_FUENTE VARCHAR(36) NOT NULL,
    ID_PROYECTO VARCHAR(36) NOT NULL,
    COD_FUENTE VARCHAR(10) NOT NULL,
    DESC_FUENTE VARCHAR(100) NOT NULL,
    VALOR_ASIGNADO BIGINT NOT NULL,
    PORCENTAJE VARCHAR(5),
    TIPO_RECURSO VARCHAR(50),
    CENTRO_COSTO VARCHAR(50),
    FEC_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_GP_FUENTE_RECURSOS PRIMARY KEY (ID_FUENTE),
    CONSTRAINT FK_GP_FUENTE_PROYECTO FOREIGN KEY (ID_PROYECTO)
        REFERENCES GP_PROYECTOS(ID_PROYECTO) ON DELETE CASCADE
);

CREATE INDEX IDX_GP_FUENTE_PROYECTO ON GP_FUENTE_RECURSOS(ID_PROYECTO);

COMMENT ON TABLE GP_FUENTE_RECURSOS IS 'P-004C: Fuente de Recursos y Centro de Costos';

-- -----------------------------------------------------------------------------
-- P-011A: Cobertura Proyectada
-- -----------------------------------------------------------------------------
CREATE TABLE GP_COBERTURA_PROYECTADA (
    ID_COBERTURA VARCHAR(36) NOT NULL,
    ID_PROYECTO VARCHAR(36) NOT NULL,
    COD_CATEGORIA INTEGER NOT NULL,
    CANTIDAD_BENEFICIARIOS INTEGER NOT NULL,
    VALOR_PER_CAPITA BIGINT,
    ANIO1 INTEGER,
    ANIO2 INTEGER,
    ANIO3 INTEGER,
    ANIO4 INTEGER,
    ANIO5 INTEGER,
    FEC_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_GP_COBERTURA_PROYECTADA PRIMARY KEY (ID_COBERTURA),
    CONSTRAINT FK_GP_COBERTURA_PROYECTO FOREIGN KEY (ID_PROYECTO)
        REFERENCES GP_PROYECTOS(ID_PROYECTO) ON DELETE CASCADE
);

CREATE INDEX IDX_GP_COBERTURA_PROYECTO ON GP_COBERTURA_PROYECTADA(ID_PROYECTO);

COMMENT ON TABLE GP_COBERTURA_PROYECTADA IS 'P-011A: Cobertura Proyectada - Proyeccion a 5 anos';

-- -----------------------------------------------------------------------------
-- P-011B: Cobertura Ejecutada
-- -----------------------------------------------------------------------------
CREATE TABLE GP_COBERTURA_EJECUTADA (
    ID_COBERTURA_EJEC VARCHAR(36) NOT NULL,
    ID_PROYECTO VARCHAR(36) NOT NULL,
    COD_CATEGORIA INTEGER NOT NULL,
    CANTIDAD_BENEFICIARIOS INTEGER NOT NULL,
    VALOR_PER_CAPITA BIGINT,
    ANIO1_EJECUTADO INTEGER,
    ANIO2_EJECUTADO INTEGER,
    ANIO3_EJECUTADO INTEGER,
    ANIO4_EJECUTADO INTEGER,
    ANIO5_EJECUTADO INTEGER,
    OBSERVACIONES VARCHAR(2000),
    FEC_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_GP_COBERTURA_EJECUTADA PRIMARY KEY (ID_COBERTURA_EJEC),
    CONSTRAINT FK_GP_COBERTURA_EJEC_PROYECTO FOREIGN KEY (ID_PROYECTO)
        REFERENCES GP_PROYECTOS(ID_PROYECTO) ON DELETE CASCADE
);

COMMENT ON TABLE GP_COBERTURA_EJECUTADA IS 'P-011B: Cobertura Ejecutada - Informacion real';

-- -----------------------------------------------------------------------------
-- P-012A: Seguimiento del Proyecto
-- -----------------------------------------------------------------------------
CREATE TABLE GP_SEGUIMIENTO (
    ID_SEGUIMIENTO VARCHAR(36) NOT NULL,
    ID_PROYECTO VARCHAR(36) NOT NULL,
    PERIODO_REPORTE VARCHAR(8) NOT NULL,
    TIPO_ACTIVIDAD VARCHAR(5) NOT NULL,
    DESCRIPCION_ACTIVIDAD VARCHAR(500),
    PORCENTAJE_EJECUTADO VARCHAR(5),
    VALOR_PLANEADO BIGINT,
    VALOR_EJECUTADO BIGINT,
    COSTO_ACTUAL BIGINT,
    VALOR_PAGADO BIGINT,
    VALOR_GANADO BIGINT,
    CANTIDAD_EJECUCION_FISICA BIGINT,
    FECHA_INICIO VARCHAR(8),
    FECHA_TERMINACION VARCHAR(8),
    OBSERVACIONES VARCHAR(2000),
    FEC_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_GP_SEGUIMIENTO PRIMARY KEY (ID_SEGUIMIENTO),
    CONSTRAINT FK_GP_SEGUIMIENTO_PROYECTO FOREIGN KEY (ID_PROYECTO)
        REFERENCES GP_PROYECTOS(ID_PROYECTO) ON DELETE CASCADE
);

CREATE INDEX IDX_GP_SEGUIMIENTO_PROYECTO ON GP_SEGUIMIENTO(ID_PROYECTO);
CREATE INDEX IDX_GP_SEGUIMIENTO_PERIODO ON GP_SEGUIMIENTO(PERIODO_REPORTE);

COMMENT ON TABLE GP_SEGUIMIENTO IS 'P-012A: Seguimiento del Proyecto';

-- -----------------------------------------------------------------------------
-- P-013A: Aspectos Especificos Infraestructura
-- -----------------------------------------------------------------------------
CREATE TABLE GP_INFRAESTRUCTURA (
    ID_INFRAESTRUCTURA VARCHAR(36) NOT NULL,
    ID_PROYECTO VARCHAR(36) NOT NULL,
    INTERVENTORIA_SUPERVISION INTEGER NOT NULL,
    VALOR_TOTAL_INTERVENTORIA BIGINT,
    LICENCIA_CONSTRUCCION INTEGER NOT NULL,
    ENT_COMPETENTE VARCHAR(250),
    NUM_RADICADO_SOLICITUD_LICENCIA VARCHAR(30),
    FECHA_RADICACION_SOLICITUD_LICENCIA VARCHAR(8),
    NUMERO_LICENCIA VARCHAR(250),
    FECHA_LICENCIA VARCHAR(250),
    VIGENCIA_LICENCIA VARCHAR(50),
    SERVICIOS_PUBLICOS INTEGER NOT NULL,
    FECHA_RADICACION_AAA VARCHAR(8),
    NUM_RADICADO_SOLICITUD_AAA VARCHAR(30),
    FECHA_EXPEDICION_AAA VARCHAR(8),
    NUM_DISPONIBILIDAD_AAA VARCHAR(30),
    VIGENCIA_AAA INTEGER,
    FECHA_RADICACION_EEA VARCHAR(8),
    NUM_RADICADO_SOLICITUD_EEA VARCHAR(30),
    FECHA_EXPEDICION_EEA VARCHAR(8),
    NUM_DISPONIBILIDAD_EEA VARCHAR(30),
    VIGENCIA_EEA INTEGER,
    FECHA_RADICACION_GNA VARCHAR(8),
    NUM_RADICADO_SOLICITUD_GNA VARCHAR(30),
    FECHA_EXPEDICION_GNA VARCHAR(8),
    NUM_DISPONIBILIDAD_GNA VARCHAR(30),
    VIGENCIA_GNA INTEGER,
    PROYECCION_GENERACION_EMPLEO INTEGER,
    FEC_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_GP_INFRAESTRUCTURA PRIMARY KEY (ID_INFRAESTRUCTURA),
    CONSTRAINT FK_GP_INFRAESTRUCTURA_PROYECTO FOREIGN KEY (ID_PROYECTO)
        REFERENCES GP_PROYECTOS(ID_PROYECTO) ON DELETE CASCADE
);

COMMENT ON TABLE GP_INFRAESTRUCTURA IS 'P-013A: Aspectos Especificos Infraestructura';

-- -----------------------------------------------------------------------------
-- P-023A: Fondos de Credito
-- -----------------------------------------------------------------------------
CREATE TABLE GP_FONDOS_CREDITO (
    ID_FONDO VARCHAR(36) NOT NULL,
    ID_PROYECTO VARCHAR(36) NOT NULL,
    MODALIDAD_CREDITO INTEGER NOT NULL,
    COD_CATEGORIA INTEGER NOT NULL,
    TASA_INTERES_MINIMA VARCHAR(5) NOT NULL,
    TASA_INTERES_MAXIMA VARCHAR(5) NOT NULL,
    CANT_CREDITOS INTEGER NOT NULL,
    VAL_MONTO_CREDITOS BIGINT NOT NULL,
    PLAZO_CREDITO INTEGER NOT NULL,
    PORCENTAJE_SUBSIDIO VARCHAR(5) NOT NULL,
    FEC_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_GP_FONDOS_CREDITO PRIMARY KEY (ID_FONDO),
    CONSTRAINT FK_GP_FONDOS_PROYECTO FOREIGN KEY (ID_PROYECTO)
        REFERENCES GP_PROYECTOS(ID_PROYECTO) ON DELETE CASCADE
);

CREATE INDEX IDX_GP_FONDOS_PROYECTO ON GP_FONDOS_CREDITO(ID_PROYECTO);

COMMENT ON TABLE GP_FONDOS_CREDITO IS 'P-023A: Constitucion/Amplacion Fondos de Credito';

-- -----------------------------------------------------------------------------
-- P-024A: Cartera por Edades
-- -----------------------------------------------------------------------------
CREATE TABLE GP_CARTERA_EDADES (
    ID_CARTERA VARCHAR(36) NOT NULL,
    ID_PROYECTO VARCHAR(36) NOT NULL,
    RAN_EDAD VARCHAR(2) NOT NULL,
    EDAD_CARTERA INTEGER NOT NULL,
    MODALIDAD_CREDITO INTEGER NOT NULL,
    COD_CATEGORIA INTEGER NOT NULL,
    CANT_CREDITOS INTEGER NOT NULL,
    VALOR_TOTAL_MONTO_CARTERA BIGINT NOT NULL,
    FEC_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_GP_CARTERA_EDADES PRIMARY KEY (ID_CARTERA),
    CONSTRAINT FK_GP_CARTERA_PROYECTO FOREIGN KEY (ID_PROYECTO)
        REFERENCES GP_PROYECTOS(ID_PROYECTO) ON DELETE CASCADE
);

CREATE INDEX IDX_GP_CARTERA_PROYECTO ON GP_CARTERA_EDADES(ID_PROYECTO);

COMMENT ON TABLE GP_CARTERA_EDADES IS 'P-024A: Cartera por Edades';

-- -----------------------------------------------------------------------------
-- P-026A: Arrendamiento Bienes Inmuebles
-- -----------------------------------------------------------------------------
CREATE TABLE GP_ARRENDAMIENTO (
    ID_ARRENDAMIENTO VARCHAR(36) NOT NULL,
    ID_PROYECTO VARCHAR(36) NOT NULL,
    FEC_CERT_TRADICION_LIBERTAD VARCHAR(8) NOT NULL,
    FEC_AVALUO VARCHAR(8) NOT NULL,
    PERITO VARCHAR(50) NOT NULL,
    VALOR_AVALUO BIGINT NOT NULL,
    VAL_CANON_MENSUAL BIGINT NOT NULL,
    TMP_CONTRATO INTEGER NOT NULL,
    DESTINACION_INMUEBLE VARCHAR(50) NOT NULL,
    USO_AUTORIZADO VARCHAR(50) NOT NULL,
    FEC_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_GP_ARRENDAMIENTO PRIMARY KEY (ID_ARRENDAMIENTO),
    CONSTRAINT FK_GP_ARRENDAMIENTO_PROYECTO FOREIGN KEY (ID_PROYECTO)
        REFERENCES GP_PROYECTOS(ID_PROYECTO) ON DELETE CASCADE
);

COMMENT ON TABLE GP_ARRENDAMIENTO IS 'P-026A: Arrendamiento Bienes Inmuebles';

-- -----------------------------------------------------------------------------
-- P-031A: Comodato Bienes Inmuebles
-- -----------------------------------------------------------------------------
CREATE TABLE GP_COMODATO (
    ID_COMODATO VARCHAR(36) NOT NULL,
    ID_PROYECTO VARCHAR(36) NOT NULL,
    FEC_CERT_TRADICION_LIBERTAD VARCHAR(8) NOT NULL,
    DESTINACION_INMUEBLE VARCHAR(50) NOT NULL,
    USO_AUTORIZADO VARCHAR(50) NOT NULL,
    FEC_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_GP_COMODATO PRIMARY KEY (ID_COMODATO),
    CONSTRAINT FK_GP_COMODATO_PROYECTO FOREIGN KEY (ID_PROYECTO)
        REFERENCES GP_PROYECTOS(ID_PROYECTO) ON DELETE CASCADE
);

COMMENT ON TABLE GP_COMODATO IS 'P-031A: Comodato Bienes Inmuebles';

-- -----------------------------------------------------------------------------
-- P-034A: Compra Bienes Inmuebles
-- -----------------------------------------------------------------------------
CREATE TABLE GP_COMPRA_INMUEBLES (
    ID_COMPRA VARCHAR(36) NOT NULL,
    ID_PROYECTO VARCHAR(36) NOT NULL,
    FEC_CERT_TRADICION_LIBERTAD VARCHAR(8) NOT NULL,
    FEC_AVALUO VARCHAR(8) NOT NULL,
    PERITO VARCHAR(50) NOT NULL,
    VALOR_AVALUO BIGINT NOT NULL,
    DESTINACION_INMUEBLE VARCHAR(50) NOT NULL,
    USO_AUTORIZADO VARCHAR(50) NOT NULL,
    FEC_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_GP_COMPRA_INMUEBLES PRIMARY KEY (ID_COMPRA),
    CONSTRAINT FK_GP_COMPRA_PROYECTO FOREIGN KEY (ID_PROYECTO)
        REFERENCES GP_PROYECTOS(ID_PROYECTO) ON DELETE CASCADE
);

COMMENT ON TABLE GP_COMPRA_INMUEBLES IS 'P-034A: Compra Bienes Inmuebles';

-- -----------------------------------------------------------------------------
-- P-040A: Permuta Bienes Inmuebles
-- -----------------------------------------------------------------------------
CREATE TABLE GP_PERMUTA (
    ID_PERMUTA VARCHAR(36) NOT NULL,
    ID_PROYECTO VARCHAR(36) NOT NULL,
    FEC_CERT_TRADICION_LIBERTAD VARCHAR(8) NOT NULL,
    FEC_AVALUO_RECIBE VARCHAR(8) NOT NULL,
    FEC_AVALUO_ENTREGA VARCHAR(8) NOT NULL,
    AVALUADOR_RECIBE VARCHAR(50) NOT NULL,
    AVALUADOR_ENTREGA VARCHAR(50) NOT NULL,
    VAL_AVALUO_RECIBE BIGINT NOT NULL,
    VAL_AVALUO_ENTREGA BIGINT NOT NULL,
    DESTINACION_INMUEBLE VARCHAR(50) NOT NULL,
    USO_AUTORIZADO VARCHAR(50) NOT NULL,
    VAL_LIBROS BIGINT NOT NULL,
    UTILIDAD_PERDIDA BIGINT NOT NULL,
    ORIGEN_RECURSOS VARCHAR(30) NOT NULL,
    DESTINACION_RECURSOS VARCHAR(80) NOT NULL,
    FEC_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_GP_PERMUTA PRIMARY KEY (ID_PERMUTA),
    CONSTRAINT FK_GP_PERMUTA_PROYECTO FOREIGN KEY (ID_PROYECTO)
        REFERENCES GP_PROYECTOS(ID_PROYECTO) ON DELETE CASCADE
);

COMMENT ON TABLE GP_PERMUTA IS 'P-040A: Permuta Bienes Inmuebles';

-- -----------------------------------------------------------------------------
-- P-050A: Negociacion Acciones/Cuotas/Partes
-- -----------------------------------------------------------------------------
CREATE TABLE GP_NEGOCIACION_ACCIONES (
    ID_NEGOCIACION VARCHAR(36) NOT NULL,
    ID_PROYECTO VARCHAR(36) NOT NULL,
    NUM_ACCIONES_CUOTAS INTEGER NOT NULL,
    VALOR_ACCIONES_CUOTAS BIGINT NOT NULL,
    PORCENTAJE_PARTICIPACION VARCHAR(5) NOT NULL,
    VALOR_NOMINAL_ACCIONES BIGINT NOT NULL,
    VALOR_MERCADO_ACCIONES BIGINT NOT NULL,
    FEC_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_GP_NEGOCIACION_ACCIONES PRIMARY KEY (ID_NEGOCIACION),
    CONSTRAINT FK_GP_NEGOCIACION_PROYECTO FOREIGN KEY (ID_PROYECTO)
        REFERENCES GP_PROYECTOS(ID_PROYECTO) ON DELETE CASCADE
);

COMMENT ON TABLE GP_NEGOCIACION_ACCIONES IS 'P-050A: Negociacion Acciones/Cuotas/Partes';

-- -----------------------------------------------------------------------------
-- P-055A: Capitalizaciones
-- -----------------------------------------------------------------------------
CREATE TABLE GP_CAPITALIZACIONES (
    ID_CAPITALIZACION VARCHAR(36) NOT NULL,
    ID_PROYECTO VARCHAR(36) NOT NULL,
    NUM_ACCIONES_CUOTAS INTEGER NOT NULL,
    VALOR_ACCIONES_CUOTAS BIGINT NOT NULL,
    PORCENTAJE_PARTICIPACION VARCHAR(5) NOT NULL,
    VALOR_NOMINAL_ACCIONES BIGINT NOT NULL,
    VALOR_MERCADO_ACCIONES BIGINT NOT NULL,
    FEC_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_GP_CAPITALIZACIONES PRIMARY KEY (ID_CAPITALIZACION),
    CONSTRAINT FK_GP_CAPITALIZACION_PROYECTO FOREIGN KEY (ID_PROYECTO)
        REFERENCES GP_PROYECTOS(ID_PROYECTO) ON DELETE CASCADE
);

COMMENT ON TABLE GP_CAPITALIZACIONES IS 'P-055A: Capitalizaciones';

-- -----------------------------------------------------------------------------
-- Tabla de Documentos PDF
-- -----------------------------------------------------------------------------
CREATE TABLE GP_DOCUMENTOS (
    ID_DOCUMENTO VARCHAR(36) NOT NULL,
    ID_PROYECTO VARCHAR(36) NOT NULL,
    COD_ESTRUCTURA VARCHAR(10) NOT NULL,
    NOMBRE_DOCUMENTO VARCHAR(200) NOT NULL,
    RUTA_ARCHIVO VARCHAR(500) NOT NULL,
    TIPO_DOCUMENTO VARCHAR(50) NOT NULL,
    TAMANO_BYTES BIGINT,
    HASH_ARCHIVO VARCHAR(64),
    USUARIO_SUBIO VARCHAR(50),
    FECHA_SUBIDA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ESTADO VARCHAR(20) DEFAULT 'ACTIVO',
    CONSTRAINT PK_GP_DOCUMENTOS PRIMARY KEY (ID_DOCUMENTO),
    CONSTRAINT FK_GP_DOCUMENTOS_PROYECTO FOREIGN KEY (ID_PROYECTO)
        REFERENCES GP_PROYECTOS(ID_PROYECTO) ON DELETE CASCADE
);

CREATE INDEX IDX_GP_DOCUMENTOS_PROYECTO ON GP_DOCUMENTOS(ID_PROYECTO);
CREATE INDEX IDX_GP_DOCUMENTOS_ESTRUCTURA ON GP_DOCUMENTOS(COD_ESTRUCTURA);

COMMENT ON TABLE GP_DOCUMENTOS IS 'Almacenamiento de documentos PDF por estructura';

-- ============================================================================
-- SECCION 2: PROYECTOS FOVIS (P-001F a P-050F)
-- ============================================================================

-- -----------------------------------------------------------------------------
-- Tabla principal de Proyectos FOVIS - Llave primaria UUID
-- -----------------------------------------------------------------------------
CREATE TABLE FV_PROYECTOS (
    ID_PROYECTO_FOVIS VARCHAR(36) NOT NULL,
    COD_PROYECTO VARCHAR(15) NOT NULL,
    VAL_TOTAL_PROYECTO BIGINT NOT NULL,
    MODALIDAD_FOVIS INTEGER NOT NULL,
    DESCRIPCION_PROYECTO VARCHAR(4000) NOT NULL,
    OBJETIVO_PROYECTO VARCHAR(4000) NOT NULL,
    JUSTIFICACION VARCHAR(4000) NOT NULL,
    APROBACION INTEGER NOT NULL,
    NUM_ACTA_AEI BIGINT,
    FECHA_APR_AEI VARCHAR(8),
    NUM_CONSEJEROS INTEGER NOT NULL,
    TMP_REINTEGRO INTEGER,
    ESTUDIO_MERCADO VARCHAR(4000),
    EVALUACION_SOCIAL VARCHAR(4000),
    EVALUACION_FINANCIERA VARCHAR(4000),
    NUM_PERSONAS_REFERENCE BIGINT,
    NUM_POBLACION_AFECTADA BIGINT,
    FECHA_DESEMBOLSO VARCHAR(8),
    FEC_REINTEGRO VARCHAR(8),
    ESTADO_PROYECTO VARCHAR(20) DEFAULT 'BORRADOR',
    FEC_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FEC_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USUARIO_CREACION VARCHAR(50),
    USUARIO_MODIFICACION VARCHAR(50),
    CONSTRAINT PK_FV_PROYECTOS PRIMARY KEY (ID_PROYECTO_FOVIS)
);

CREATE UNIQUE INDEX UX_FV_PROYECTOS_CODIGO ON FV_PROYECTOS(COD_PROYECTO);

COMMENT ON TABLE FV_PROYECTOS IS 'Tabla principal de proyectos FOVIS - UUID como PK';

-- -----------------------------------------------------------------------------
-- P-002F: Cronograma FOVIS
-- -----------------------------------------------------------------------------
CREATE TABLE FV_CRONOGRAMA (
    ID_CRONOGRAMA VARCHAR(36) NOT NULL,
    ID_PROYECTO_FOVIS VARCHAR(36) NOT NULL,
    ANO_EJECUCION INTEGER NOT NULL,
    MES_EJECUCION INTEGER NOT NULL,
    PORCENTAJE_PROYECTADO INTEGER DEFAULT 0,
    CANTIDAD_CREDITOS_PROYECTADOS INTEGER DEFAULT 0,
    VALOR_CREDITOS_PROYECTADOS BIGINT DEFAULT 0,
    CONSTRAINT PK_FV_CRONOGRAMA PRIMARY KEY (ID_CRONOGRAMA),
    CONSTRAINT FK_FV_CRONOGRAMA_PROYECTO FOREIGN KEY (ID_PROYECTO_FOVIS)
        REFERENCES FV_PROYECTOS(ID_PROYECTO_FOVIS) ON DELETE CASCADE
);

-- -----------------------------------------------------------------------------
-- P-011F: Cobertura Proyectada FOVIS
-- -----------------------------------------------------------------------------
CREATE TABLE FV_COBERTURA_PROYECTADA (
    ID_COBERTURA VARCHAR(36) NOT NULL,
    ID_PROYECTO_FOVIS VARCHAR(36) NOT NULL,
    COD_CATEGORIA INTEGER NOT NULL,
    POBLACION_OBJETIVO BIGINT NOT NULL,
    ANIO1 INTEGER,
    ANIO2 INTEGER,
    ANIO3 INTEGER,
    ANIO4 INTEGER,
    ANIO5 INTEGER,
    CONSTRAINT PK_FV_COBERTURA_PROYECTADA PRIMARY KEY (ID_COBERTURA),
    CONSTRAINT FK_FV_COBERTURA_PROYECTO FOREIGN KEY (ID_PROYECTO_FOVIS)
        REFERENCES FV_PROYECTOS(ID_PROYECTO_FOVIS) ON DELETE CASCADE
);

-- -----------------------------------------------------------------------------
-- P-012F: Seguimiento FOVIS
-- -----------------------------------------------------------------------------
CREATE TABLE FV_SEGUIMIENTO (
    ID_SEGUIMIENTO VARCHAR(36) NOT NULL,
    ID_PROYECTO_FOVIS VARCHAR(36) NOT NULL,
    ANO_EJECUCION INTEGER NOT NULL,
    MES_EJECUCION INTEGER NOT NULL,
    TIPO_ACTIVIDAD VARCHAR(5) NOT NULL,
    VALOR_EJECUTADO BIGINT,
    CANTIDAD_CREDITOS_ASIGNADOS INTEGER,
    VALOR_CREDITOS_ASIGNADOS BIGINT,
    FECHA_COMPRA_LOTE VARCHAR(8),
    VALOR_TOTAL_COMPRA_LOTE BIGINT,
    VALOR_OTROS_COSTOS BIGINT,
    COMENTARIOS VARCHAR(4000),
    CONSTRAINT PK_FV_SEGUIMIENTO PRIMARY KEY (ID_SEGUIMIENTO),
    CONSTRAINT FK_FV_SEGUIMIENTO_PROYECTO FOREIGN KEY (ID_PROYECTO_FOVIS)
        REFERENCES FV_PROYECTOS(ID_PROYECTO_FOVIS) ON DELETE CASCADE
);

-- -----------------------------------------------------------------------------
-- P-014F: Aspectos VIS
-- -----------------------------------------------------------------------------
CREATE TABLE FV_ASPECTOS_VIS (
    ID_ASPECTO_VIS VARCHAR(36) NOT NULL,
    ID_PROYECTO_FOVIS VARCHAR(36) NOT NULL,
    MODALIDAD_SOLUCION_VIVIENDA VARCHAR(50),
    INTERVENTORIA_SUPERVISION INTEGER,
    ENT_COMPETENTE VARCHAR(250),
    NUM_RADICADO_LICENCIA VARCHAR(30),
    FEC_SOLICITUD_LICENCIA VARCHAR(8),
    NUMERO_LICENCIA VARCHAR(30),
    FEC_LICENCIA VARCHAR(8),
    VIGENCIA_LICENCIA INTEGER,
    FEC_RADICACION_AAA VARCHAR(8),
    NUM_RADICADO_SOLICITUD_AAA VARCHAR(30),
    FEC_EXPEDICION_AAA VARCHAR(8),
    NUM_DISPONIBILIDAD_AAA VARCHAR(30),
    VIGENCIA_AAA INTEGER,
    FEC_RADICACION_EEA VARCHAR(8),
    NUM_RADICADO_SOLICITUD_EEA VARCHAR(30),
    FEC_EXPEDICION_EEA VARCHAR(8),
    NUM_DISPONIBILIDAD_EEA VARCHAR(30),
    VIGENCIA_EEA INTEGER,
    FEC_RADICACION_GNA VARCHAR(8),
    NUM_RADICADO_SOLICITUD_GNA VARCHAR(30),
    FEC_EXPEDICION_GNA VARCHAR(8),
    NUM_DISPONIBILIDAD_GNA VARCHAR(30),
    VIGENCIA_GNA INTEGER,
    CONSTRAINT PK_FV_ASPECTOS_VIS PRIMARY KEY (ID_ASPECTO_VIS),
    CONSTRAINT FK_FV_ASPECTOS_VIS_PROYECTO FOREIGN KEY (ID_PROYECTO_FOVIS)
        REFERENCES FV_PROYECTOS(ID_PROYECTO_FOVIS) ON DELETE CASCADE
);

-- -----------------------------------------------------------------------------
-- P-022F: Tipologia VIS
-- -----------------------------------------------------------------------------
CREATE TABLE FV_TIPOLOGIA_VIS (
    ID_TIPOLOGIA VARCHAR(36) NOT NULL,
    ID_PROYECTO_FOVIS VARCHAR(36) NOT NULL,
    COD_TIPOLOGIA INTEGER NOT NULL,
    AREA_UNIDAD_CONSTRUCCION VARCHAR(5),
    VALOR_VENTA BIGINT NOT NULL,
    NUMERO_UNIDADES INTEGER NOT NULL,
    CONSTRAINT PK_FV_TIPOLOGIA_VIS PRIMARY KEY (ID_TIPOLOGIA),
    CONSTRAINT FK_FV_TIPOLOGIA_PROYECTO FOREIGN KEY (ID_PROYECTO_FOVIS)
        REFERENCES FV_PROYECTOS(ID_PROYECTO_FOVIS) ON DELETE CASCADE
);

-- -----------------------------------------------------------------------------
-- P-023F: Creditos Hipotecarios
-- -----------------------------------------------------------------------------
CREATE TABLE FV_CREDITOS_HIPOTECARIOS (
    ID_CREDITO_HIP VARCHAR(36) NOT NULL,
    ID_PROYECTO_FOVIS VARCHAR(36) NOT NULL,
    VLR_INDIVIDUAL_CREDITOS BIGINT NOT NULL,
    SISTEMA_AMORTIZACION VARCHAR(200),
    TAS_INTERES VARCHAR(5) NOT NULL,
    PUNTOS_ADICIONALES VARCHAR(5),
    PLAZO_FINANCIACION INTEGER NOT NULL,
    REQUISITOS_GARANTIAS VARCHAR(4000),
    ESTRATEGIAS_RECUPERACION VARCHAR(4000),
    PROCESOS_ADMINISTRATIVOS VARCHAR(4000),
    CONSTRAINT PK_FV_CREDITOS_HIPOTECARIOS PRIMARY KEY (ID_CREDITO_HIP),
    CONSTRAINT FK_FV_CREDITOS_PROYECTO FOREIGN KEY (ID_PROYECTO_FOVIS)
        REFERENCES FV_PROYECTOS(ID_PROYECTO_FOVIS) ON DELETE CASCADE
);

-- -----------------------------------------------------------------------------
-- P-039F: Adquisicion de Lotes
-- -----------------------------------------------------------------------------
CREATE TABLE FV_ADQUISICION_LOTES (
    ID_LOTE VARCHAR(36) NOT NULL,
    ID_PROYECTO_FOVIS VARCHAR(36) NOT NULL,
    AREA_LOTE VARCHAR(10),
    VALOR_LOTE BIGINT NOT NULL,
    VALOR_OTROS_COSTOS BIGINT,
    FEC_AVALUO VARCHAR(8),
    PERITO VARCHAR(50),
    NUM_REGISTRO_AVALUADOR VARCHAR(20),
    VALOR_AVALUO BIGINT,
    FEC_CERT_TRADICION_LIBERTAD VARCHAR(8),
    SERVICIOS_PUBLICOS INTEGER,
    CONSTRAINT PK_FV_ADQUISICION_LOTES PRIMARY KEY (ID_LOTE),
    CONSTRAINT FK_FV_LOTES_PROYECTO FOREIGN KEY (ID_PROYECTO_FOVIS)
        REFERENCES FV_PROYECTOS(ID_PROYECTO_FOVIS) ON DELETE CASCADE
);

-- -----------------------------------------------------------------------------
-- P-049F: Renovacion Urbana
-- -----------------------------------------------------------------------------
CREATE TABLE FV_RENOVACION_URBANA (
    ID_RENOVACION VARCHAR(36) NOT NULL,
    ID_PROYECTO_FOVIS VARCHAR(36) NOT NULL,
    NUM_SOLUCIONES_VIV INTEGER NOT NULL,
    CONSTRAINT PK_FV_RENOVACION_URBANA PRIMARY KEY (ID_RENOVACION),
    CONSTRAINT FK_FV_RENOVACION_PROYECTO FOREIGN KEY (ID_PROYECTO_FOVIS)
        REFERENCES FV_PROYECTOS(ID_PROYECTO_FOVIS) ON DELETE CASCADE
);

-- ============================================================================
-- SECCION 3: TABLAS DE SISTEMA
-- ============================================================================

-- -----------------------------------------------------------------------------
-- Control de Reportes XML
-- -----------------------------------------------------------------------------
CREATE TABLE SYS_CONTROL_REPORTES (
    ID_REPORTE VARCHAR(36) NOT NULL,
    ID_PROYECTO VARCHAR(36),
    COD_ESTRUCTURA VARCHAR(10) NOT NULL,
    PERIODO_REPORTE VARCHAR(6) NOT NULL,
    FECHA_REPORTE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USUARIO_REPORTE VARCHAR(50) NOT NULL,
    ESTADO_REPORTE VARCHAR(20) NOT NULL,
    HASH_XML VARCHAR(64),
    RUTA_XML VARCHAR(500),
    CONSTRAINT PK_SYS_CONTROL_REPORTES PRIMARY KEY (ID_REPORTE),
    CONSTRAINT FK_SYS_REPORTES_PROYECTO FOREIGN KEY (ID_PROYECTO)
        REFERENCES GP_PROYECTOS(ID_PROYECTO) ON DELETE SET NULL
);

CREATE INDEX IDX_SYS_REPORTES_PROYECTO ON SYS_CONTROL_REPORTES(ID_PROYECTO);

-- -----------------------------------------------------------------------------
-- Log de Modificaciones (Auditoria)
-- -----------------------------------------------------------------------------
CREATE TABLE SYS_LOG_MODIFICACIONES (
    ID_LOG VARCHAR(36) NOT NULL,
    ID_PROYECTO VARCHAR(36),
    TABLA_AFECTADA VARCHAR(50) NOT NULL,
    CAMPO_AFECTADO VARCHAR(50),
    VALOR_ANTERIOR VARCHAR(500),
    VALOR_NUEVO VARCHAR(500),
    USUARIO_MODIFICO VARCHAR(50) NOT NULL,
    FECHA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACCION VARCHAR(20) NOT NULL,
    CONSTRAINT PK_SYS_LOG_MODIFICACIONES PRIMARY KEY (ID_LOG)
);

CREATE INDEX IDX_SYS_LOG_PROYECTO ON SYS_LOG_MODIFICACIONES(ID_PROYECTO);
CREATE INDEX IDX_SYS_LOG_FECHA ON SYS_LOG_MODIFICACIONES(FECHA_MODIFICACION);

-- -----------------------------------------------------------------------------
-- Tabla de Parametros del Sistema
-- -----------------------------------------------------------------------------
CREATE TABLE SYS_PARAMETROS (
    PARAMETRO VARCHAR(50) NOT NULL,
    VALOR VARCHAR(500) NOT NULL,
    DESCRIPCION VARCHAR(200),
    FECHA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USUARIO_MODIFICO VARCHAR(50),
    CONSTRAINT PK_SYS_PARAMETROS PRIMARY KEY (PARAMETRO)
);

COMMENT ON TABLE SYS_PARAMETROS IS 'Parametros de configuracion del sistema';

-- -----------------------------------------------------------------------------
-- Tabla de Estructuras (Referencia)
-- -----------------------------------------------------------------------------
CREATE TABLE SYS_ESTRUCTURAS (
    COD_ESTRUCTURA VARCHAR(10) NOT NULL,
    NOMBRE_ESTRUCTURA VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(500),
    PERIODICIDAD VARCHAR(50),
    ES_OBLIGATORIA CHAR(1) DEFAULT 'S',
    ORDEN_EJECUCION INTEGER,
    CODIGO_XSD VARCHAR(100),
    FECHA_VIGENCIA TIMESTAMP,
    CONSTRAINT PK_SYS_ESTRUCTURAS PRIMARY KEY (COD_ESTRUCTURA)
);

-- Insertar estructuras por defecto
INSERT INTO SYS_ESTRUCTURAS (COD_ESTRUCTURA, NOMBRE_ESTRUCTURA, DESCRIPCION, PERIODICIDAD, ES_OBLIGATORIA, ORDEN_EJECUCION) VALUES
('P-001A', 'Datos Generales', 'Estructuras Generales Proyectos Nuevos', 'UNICO', 'S', 1),
('P-002A', 'Cronograma', 'Cronograma Inicial del Proyecto', 'UNICO', 'S', 2),
('P-003A', 'Localizacion', 'Localizacion del Proyecto', 'UNICO', 'S', 3),
('P-004C', 'Fuentes Recursos', 'Estructura Fuente de Recursos', 'UNICO', 'S', 4),
('P-011A', 'Cobertura Proyectada', 'Cobertura Proyectada 5 anios', 'UNICO', 'S', 5),
('P-012A', 'Seguimiento', 'Seguimiento del Proyecto', 'TRIMESTRAL', 'S', 6),
('P-013A', 'Infraestructura', 'Aspectos Especificos Infraestructura', 'UNICO', 'S', 7),
('P-023A', 'Fondos Credito', 'Aspectos Fondos de Credito', 'UNICO', 'S', 8),
('P-024A', 'Cartera Edades', 'Cartera por Edades', 'ANUAL', 'S', 9),
('P-026A', 'Arrendamiento', 'Arrendamiento Bienes Inmuebles', 'UNICO', 'N', 10),
('P-031A', 'Comodato', 'Comodato Bienes Inmuebles', 'UNICO', 'N', 11),
('P-034A', 'Compra', 'Compra Bienes Inmuebles', 'UNICO', 'N', 12),
('P-040A', 'Permuta', 'Permuta Bienes Inmuebles', 'UNICO', 'N', 13),
('P-050A', 'Negociacion', 'Negociacion Acciones/Cuotas', 'UNICO', 'N', 14),
('P-055A', 'Capitalizacion', 'Capitalizaciones', 'UNICO', 'N', 15);

-- ============================================================================
-- SECCION JPA: backend Spring (REST /v1/proyectos, P-001A persistencia)
-- ============================================================================

CREATE TABLE PROYECTO (
    ID_PROYECTO VARCHAR(36) NOT NULL,
    COD_PROYECTO VARCHAR(15) NOT NULL,
    NOMBRE VARCHAR(200) NOT NULL,
    MODALIDAD_INVERSION VARCHAR(3) NOT NULL,
    VALOR_TOTAL BIGINT NOT NULL,
    VALOR_APROBADO BIGINT NOT NULL,
    JUSTIFICACION VARCHAR(4000),
    ESTADO VARCHAR(20) NOT NULL,
    FECHA_CREACION DATE NOT NULL,
    ULTIMA_ACTUALIZACION TIMESTAMP NOT NULL,
    VERSION BIGINT,
    CONSTRAINT PK_PROYECTO PRIMARY KEY (ID_PROYECTO),
    CONSTRAINT UK_PROYECTO_COD_PROYECTO UNIQUE (COD_PROYECTO)
);

COMMENT ON TABLE PROYECTO IS 'Proyecto (modelo JPA REST /v1/proyectos)';

CREATE TABLE PROYECTO_ESTRUCTURAS (
    ID_PROYECTO VARCHAR(36) NOT NULL,
    NOMBRE_ESTRUCTURA VARCHAR(255) NOT NULL,
    CONSTRAINT PK_PROYECTO_ESTRUCTURAS PRIMARY KEY (ID_PROYECTO, NOMBRE_ESTRUCTURA),
    CONSTRAINT FK_PROYECTO_EST_PROYECTO FOREIGN KEY (ID_PROYECTO)
        REFERENCES PROYECTO (ID_PROYECTO) ON DELETE CASCADE
);

COMMENT ON TABLE PROYECTO_ESTRUCTURAS IS 'Estructuras completadas por proyecto (JPA @ElementCollection)';

CREATE TABLE P001A_DATOS_GENERALES (
    ID VARCHAR(36) NOT NULL,
    COD_PROYECTO VARCHAR(15) NOT NULL,
    NOMBRE_PROYECTO VARCHAR(200) NOT NULL,
    MODALIDAD_INVERSION VARCHAR(3) NOT NULL,
    VALOR_TOTAL_PROYECTO BIGINT NOT NULL,
    VALOR_APROBADO_VIGENCIA BIGINT NOT NULL,
    JUSTIFICACION VARCHAR(4000),
    OBJETIVOS VARCHAR(2000),
    RESOLUCION_AEI INTEGER,
    NUM_ACTA VARCHAR(20),
    FECHA_CONSEJO VARCHAR(8),
    NUM_CONSEJEROS INTEGER,
    TIEMPO_RECUPERACION INTEGER,
    TASA_DESCUENTO VARCHAR(10),
    NUMERO_BENEFICIARIOS BIGINT,
    DESCRIPCION_OBJETIVO VARCHAR(1000),
    FECHA_CREACION TIMESTAMP,
    FECHA_ACTUALIZACION TIMESTAMP,
    VERSION BIGINT,
    CONSTRAINT PK_P001A_DATOS_GENERALES PRIMARY KEY (ID)
);

COMMENT ON TABLE P001A_DATOS_GENERALES IS 'P-001A datos generales (JPA P001AEntity)';

CREATE UNIQUE INDEX UX_P001A_COD_PROYECTO ON P001A_DATOS_GENERALES (COD_PROYECTO);

-- ============================================================================
-- FIN DEL SCRIPT
-- ============================================================================